<?php

namespace DoctrineORMModule\Proxy\__CG__\Avaliacao\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Veiculo extends \Avaliacao\Entity\Veiculo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'idBot', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'placa', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'renavam', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'marca', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'modelo', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'ano', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'anoModelo', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'cor', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'proprietarioDoc', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'marcaFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'modeloFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'anoFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'codigoFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'valorFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'status', 'debitos', 'avaliacoes', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'id', 'active', 'created', 'updated', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'cliente'];
        }

        return ['__isInitialized__', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'idBot', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'placa', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'renavam', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'marca', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'modelo', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'ano', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'anoModelo', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'cor', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'proprietarioDoc', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'marcaFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'modeloFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'anoFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'codigoFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'valorFipe', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'status', 'debitos', 'avaliacoes', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'id', 'active', 'created', 'updated', '' . "\0" . 'Avaliacao\\Entity\\Veiculo' . "\0" . 'cliente'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Veiculo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdBot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBot', []);

        return parent::getIdBot();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdBot($idBot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdBot', [$idBot]);

        return parent::setIdBot($idBot);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaca($placa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaca', [$placa]);

        return parent::setPlaca($placa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaca', []);

        return parent::getPlaca();
    }

    /**
     * {@inheritDoc}
     */
    public function setRenavam($renavam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRenavam', [$renavam]);

        return parent::setRenavam($renavam);
    }

    /**
     * {@inheritDoc}
     */
    public function getRenavam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRenavam', []);

        return parent::getRenavam();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($marca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', [$marca]);

        return parent::setMarca($marca);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', []);

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelo($modelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelo', [$modelo]);

        return parent::setModelo($modelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelo', []);

        return parent::getModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAno($ano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAno', [$ano]);

        return parent::setAno($ano);
    }

    /**
     * {@inheritDoc}
     */
    public function getAno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAno', []);

        return parent::getAno();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnoModelo($anoModelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnoModelo', [$anoModelo]);

        return parent::setAnoModelo($anoModelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnoModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnoModelo', []);

        return parent::getAnoModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCor($cor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCor', [$cor]);

        return parent::setCor($cor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCor', []);

        return parent::getCor();
    }

    /**
     * {@inheritDoc}
     */
    public function setProprietarioDoc($proprietarioDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProprietarioDoc', [$proprietarioDoc]);

        return parent::setProprietarioDoc($proprietarioDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getProprietarioDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProprietarioDoc', []);

        return parent::getProprietarioDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarcaFipe($marcaFipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarcaFipe', [$marcaFipe]);

        return parent::setMarcaFipe($marcaFipe);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarcaFipe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarcaFipe', []);

        return parent::getMarcaFipe();
    }

    /**
     * {@inheritDoc}
     */
    public function setModeloFipe($modeloFipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModeloFipe', [$modeloFipe]);

        return parent::setModeloFipe($modeloFipe);
    }

    /**
     * {@inheritDoc}
     */
    public function getModeloFipe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeloFipe', []);

        return parent::getModeloFipe();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnoFipe($anoFipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnoFipe', [$anoFipe]);

        return parent::setAnoFipe($anoFipe);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnoFipe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnoFipe', []);

        return parent::getAnoFipe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoFipe($codigoFipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoFipe', [$codigoFipe]);

        return parent::setCodigoFipe($codigoFipe);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoFipe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoFipe', []);

        return parent::getCodigoFipe();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorFipe($valorFipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorFipe', [$valorFipe]);

        return parent::setValorFipe($valorFipe);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorFipe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorFipe', []);

        return parent::getValorFipe();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getDebitos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebitos', []);

        return parent::getDebitos();
    }

    /**
     * {@inheritDoc}
     */
    public function setDebitos($debitos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebitos', [$debitos]);

        return parent::setDebitos($debitos);
    }

    /**
     * {@inheritDoc}
     */
    public function addDebito(\Avaliacao\Entity\Debito $debito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDebito', [$debito]);

        return parent::addDebito($debito);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvaliacoes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvaliacoes', []);

        return parent::getAvaliacoes();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvaliacoes($avaliacoes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvaliacoes', [$avaliacoes]);

        return parent::setAvaliacoes($avaliacoes);
    }

    /**
     * {@inheritDoc}
     */
    public function addAvaliacao(\Avaliacao\Entity\AvaliacaoFipe $avaliacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAvaliacao', [$avaliacao]);

        return parent::addAvaliacao($avaliacao);
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeApi(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeApi', [$data]);

        return parent::exchangeApi($data);
    }

    /**
     * {@inheritDoc}
     */
    public function hydrate($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hydrate', [$data]);

        return parent::hydrate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        return parent::onPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(bool $active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(\DateTime $created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(\DateTime $updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente($cliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', [$cliente]);

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

}
