<?php
$form->setAttribute('class', 'login-form');
$username = $form->get('username');
$username->setAttribute('class', 'form-control form-control-solid placeholder-no-fix')
    ->setLabelAttributes(['class' => 'control-label visible-ie8 visible-ie9"']);

$password = $form->get('password');
$password->setAttribute('class', 'form-control form-control-solid placeholder-no-fix')
    ->setLabelAttributes(['class' => 'control-label visible-ie8 visible-ie9']);

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn green uppercase');

$form->setAttribute('action', $this->url('login'));
$form->prepare();
?>

<?php if ($messageError): ?>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span>
        </button>
        <strong>Erro!</strong> <?= $messageError; ?>
    </div>
<?php endif; ?>

<?php echo $this->form()->openTag($form); ?>
    <h3 class="form-title font-green">Logar</h3>
    <div class="form-group">
        <?= $this->formLabel($username); ?>
        <?= $this->formElement($username); ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($password); ?>
        <?= $this->formElement($password); ?>
    </div>

<?php echo $this->formSubmit($submit); ?>
<!--    <label class="rememberme check mt-checkbox mt-checkbox-outline">-->
<!--        <input type="checkbox" name="remember" value="1"/>Remember-->
<!--        <span></span>-->
<!--    </label>-->
<!--    <a href="javascript:;" id="forget-password" class="forget-password">Forgot Password?</a>-->
    <div class="login-options"></div>
    <div class="create-account">
        <p>
<!--            <a href="javascript:;" id="register-btn" class="uppercase">Cadastre-se</a>-->
        </p>
    </div>
<?php
echo $this->form()->closeTag();
?>