<h1>Cadastrar Veiculo</h1>
<?php
    $placa   = $form->get('placa');
    $renavam = $form->get('renavam');
    $submit  = $form->get('submit');

    $form->setAttribute('action', $this->url(Avaliacao\Lib\Enum\RoutesEnum::VEICULO, ['action' => 'add']));
    $form->prepare();
?>
<div class="mt-element-step">
    <div class="row step-line">
        <div class="col-md-6 mt-step-col first active">
            <div class="mt-step-number bg-white">
                <i class="fa fa-car"></i>
            </div>
            <div class="mt-step-title uppercase font-grey-cascade">Veiculo</div>
            <div class="mt-step-content font-grey-cascade">Dados do veiculo</div>
        </div>
        <div class="col-md-6 mt-step-col last" href="<?= $this->url(\Avaliacao\Lib\Enum\RoutesEnum::VEICULO, ['action' => 'cliente']); ?>">
            <div class="mt-step-number bg-white">
                <i class="fa fa-user"></i>
            </div>
            <div class="mt-step-title uppercase font-grey-cascade">Cliente</div>
            <span class="mt-step-content font-grey-cascade">Dados do cliente</span>
        </div>
    </div>
</div>

<div class="portlet-body form">

    <?php echo $this->form()->openTag($form); ?>

    <?php $message = $this->formElementErrors($placa, ['class' => 'help-block']); ?>

    <div class="form-group<?= $message ? " has-error" : "" ?>">
        <?= $this->formLabel($placa); ?>
            <?= $this->formElement($placa); ?>
            <?= $message ?>
    </div>

    <?php $message = $this->formElementErrors($renavam, ['class' => 'help-block']); ?>

    <div class="form-group<?= $message ? " has-error" : "" ?>">
        <?= $this->formLabel($renavam); ?>
        <?= $this->formElement($renavam); ?>
        <?= $message ?>
    </div>

    <div class="form-actions right">
        <?php echo $this->formSubmit($submit); ?>
    </div>

    <?php
        echo $this->formHidden($form->get('id'));
        echo $this->form()->closeTag();
    ?>

</div>
