<h1>Editar Veiculo</h1>

<?php

$placa = $form->get('placa');
$placa->setAttribute('class', 'form-control')
    ->setLabelAttributes(['class' => 'control-label']);

$renavam = $form->get('renavam');
$renavam->setAttribute('class', 'form-control')
    ->setLabelAttributes(['class' => 'control-label']);

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url($this->route, ['action' => 'edit', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
?>

<?php $message = $this->formElementErrors($placa, ['class' => 'help-block']); ?>
<div class="form-group<?= $message ? " has-error" : "" ?>">
    <?= $this->formLabel($placa); ?>
    <?= $this->formElement($placa); ?>
    <?= $message ?>
</div>

<?php $message = $this->formElementErrors($renavam, ['class' => 'help-block']); ?>
<div class="form-group<?= $message ? " has-error" : "" ?>">
    <?= $this->formLabel($renavam); ?>
    <?= $this->formElement($renavam); ?>
    <?= $message ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>