<?php $this->headTitle("Veiculos"); ?>

<h1>Blog</h1>

<p>
    <a href="<?= $this->url('admin-blog/post', ['action' => 'add']); ?>">
        New Post
    </a>
</p>

<table class="table">
    <tr>
        <th>Placa</th>
        <th>Action</th>
    </tr>
    <?php foreach ($veiculos as $veiculo): ?>
        <tr>
            <td><?= $this->escapeHtml($veiculo->placa); ?></td>
            <td>
                <a href="<?= $this->url('admin-blog/post', ['action' => 'edit', 'id' => $veiculo->id]); ?>">
                    Edit
                </a>
                <a href="<?= $this->url('admin-blog/post', ['action' => 'delete', 'id' => $veiculo->id]); ?>">
                    Delete
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>