<?php
    use Avaliacao\Lib\Enum\RoutesEnum;

    $this->headTitle("Veiculos");
?>
<!-- END THEME PANEL -->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="<?= $this->url('home'); ?>">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Veiculos</span>
        </li>
    </ul>
</div>


<!-- BEGIN PAGE TITLE-->
<h1 class="page-title"> Veiculos
    <small>listagem de veiculos</small>
</h1>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- Begin: life time stats -->
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-settings font-green"></i>
                    <span class="caption-subject font-green sbold uppercase"> Listagem de Veiculos </span>
                </div>
                <div class="actions">
                    <a class="btn btn-transparent green btn-outline btn-outline btn-circle btn-sm active"
                       href="<?= $this->url($this->route, ['action' => 'add']); ?>">
                        Adicionar
                    </a>
                </div>
            </div>
            <div class="portlet-body">

                <table class="table table-striped table-bordered table-hover " width="100%" id="veiculosTable">
                    <thead>
                    <tr>
                        <th class="all">Placa</th>
                        <th class="min-phone-l">Renavam</th>
                        <th class="min-tablet">Modelo</th>
                        <th class="none">Ano</th>
                        <th class="none">Cor</th>
                        <th class="none">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($veiculos as $veiculo): ?>
                        <tr>
                            <td><?= $this->escapeHtml($veiculo->getPlaca()); ?></td>
                            <td><?= $this->escapeHtml($veiculo->getRenavam()); ?></td>
                            <td><?= $this->escapeHtml($veiculo->getModelo()); ?></td>
                            <td><?= $this->escapeHtml($veiculo->getAno()); ?></td>
                            <td><?= $this->escapeHtml($veiculo->getCor()); ?></td>
                            <td>
                                <a class="btn btn-info btn-sm"
                                   href="<?= $this->url(RoutesEnum::VEICULO, ['action' => 'view', 'id' => $veiculo->getId()]); ?>">
                                    Visualizar
                                </a>
                                <a class="btn btn-info btn-sm"
                                   href="<?= $this->url(RoutesEnum::FIPE, ['action' => 'avaliar', 'id' => $veiculo->getId()]); ?>">
                                    Avaliar
                                </a>
                                <a class="btn btn-danger btn-sm" data-toggle="confirmation"
                                   href="<?= $this->url(RoutesEnum::VEICULO, ['action' => 'delete', 'id' => $veiculo->getId()]); ?>">
                                    Deletar
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
</div>
<script>
    $(document).ready(function () {
        var table = $('#veiculosTable');

        var oTable = table.dataTable({
            // Internationalisation. For more info refer to http://datatables.net/manual/i18n
            // "language": {
            //     "aria": {
            //         "sortAscending": ": activate to sort column ascending",
            //         "sortDescending": ": activate to sort column descending"
            //     },
            //     "emptyTable": "No data available in table",
            //     "info": "Showing _START_ to _END_ of _TOTAL_ entries",
            //     "infoEmpty": "No entries found",
            //     "infoFiltered": "(filtered1 from _MAX_ total entries)",
            //     "lengthMenu": "_MENU_ entries",
            //     "search": "Search:",
            //     "zeroRecords": "No matching records found"
            // },

            // Or you can use remote translation file
            "language": {
                url: '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese.json'
            },

            // setup buttons extentension: http://datatables.net/extensions/buttons/
            buttons: [
                // { extend: 'print', className: 'btn dark btn-outline' },
                // { extend: 'pdf', className: 'btn green btn-outline' },
                // { extend: 'csv', className: 'btn purple btn-outline ' }
            ],

            // setup responsive extension: http://datatables.net/extensions/responsive/
//            responsive: {
//                details: {
//                    type: 'column',
//                    target: 'tr'
//                }
//            },
            columnDefs: [{
                className: 'control',
                orderable: false,
                targets: 0
            }],

            order: [1, 'asc'],

            // pagination control
            "lengthMenu": [
                [5, 10, 15, 20, -1],
                [5, 10, 15, 20, "All"] // change per page values here
            ],
            // set the initial value
            "pageLength": 10,
            // "pagingType": 'bootstrap_extended', // pagination type

            "dom": "<'row' <'col-md-12'B>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable

            // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
            // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
            // So when dropdowns used the scrollable div should be removed.
            //"dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",
        });
    });
</script>