<h1>Cadastrar Veiculo</h1>
<div class="mt-element-step">
    <div class="row step-line">
        <div class="col-md-4 mt-step-col first active">
            <div class="mt-step-number bg-white">
                <i class="fa fa-car"></i>
            </div>
            <div class="mt-step-title uppercase font-grey-cascade">Veiculo</div>
            <div class="mt-step-content font-grey-cascade">Dados do veiculo</div>
        </div>
        <div class="col-md-4 mt-step-col active">
            <div class="mt-step-number bg-white">
                <i class="fa fa-user"></i>
            </div>
            <div class="mt-step-title uppercase font-grey-cascade">Cliente</div>
            <div class="mt-step-content font-grey-cascade">Dados do cliente</div>
        </div>
        <div class="col-md-4 mt-step-col last">
            <div class="mt-step-number bg-white">
                <i class="fa fa-rocket"></i>
            </div>
            <div class="mt-step-title uppercase font-grey-cascade">Fipe</div>
            <div class="mt-step-content font-grey-cascade">Selecione tabela Fipe</div>
        </div>
    </div>
</div>

<form class="mt-repeater form-horizontal" role="form">
    <div class="form-body">
        <h3 class="form-section">Proprietario</h3>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Nome:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"><?= $proprietario->nome; ?></p>
                    </div>
                </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Cpf/Cnpj:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"><?= $proprietario->cpf_cnpj; ?></p>
                    </div>
                </div>
            </div>
            <!--/span-->
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Email:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"><?= $proprietario->email; ?></p>
                    </div>
                </div>
            </div>
        </div>
        <!--/row-->
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Sexo</label>
                    <div class="col-md-9">
                        <div class="col-md-9">
                            <p class="form-control-static"><?= $proprietario->sexo; ?></p>
                        </div>
                    </div>
                </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Nascimento:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"><?= $proprietario->data_nascimento; ?></p>
                    </div>
                </div>
            </div>

            <!--/span-->
        </div>
        <div class="group-telefone">

            <h5 class="form-section">Telefone</h5>
            <div data-repeater-list="group-telefone">

                <div data-repeater-item class="mt-repeater-item">
                    <!-- jQuery Repeater Container -->
                    <div class="mt-repeater-input">
                        <label class="control-label">Numero</label>
                        <br>
                        <input type="text" name="group-telefone[0][text-input]" class="form-control"
                               value="48 84571624">
                    </div>
                    <div class="mt-repeater-input">
                        <a href="javascript:;" data-repeater-delete
                           class="btn btn-danger mt-repeater-delete">
                            <i class="fa fa-close"></i> Delete</a>
                    </div>
                </div>

            </div>
            <a href="javascript:;" data-repeater-create class="btn btn-success mt-repeater-add">
                <i class="fa fa-plus"></i> Add</a>


        </div>

        <div class="group-endereco">
            <h4 class="form-section">Endereço</h4>
            <div data-repeater-list="group-endereco">

                <div data-repeater-item class="mt-repeater-item">

                    <div class="mt-repeater-input">
                        <label class="control-label">Rua</label>
                        <br>
                        <input type="text" name="group-a[0][text-input]" class="form-control form-control-inline">
                    </div>

                    <div class="mt-repeater-input">
                        <label class="control-label">Cidade</label>
                        <br>
                        <input type="text" name="group-a[0][text-input]" class="form-control form-control-inline">
                    </div>

                    <div class="mt-repeater-input">
                        <label class="control-label">Estado</label>
                        <br>
                        <input type="text" name="group-a[0][text-input]" class="form-control form-control-inline">
                    </div>

                    <div class="mt-repeater-input">
                        <label class="control-label">Cep</label>
                        <br>
                        <input type="text" name="group-a[0][text-input]" class="form-control form-control-inline">
                    </div>

                    <div class="mt-repeater-input">
                        <label class="control-label">Pais</label>
                        <br>
                        <input type="text" name="group-a[0][text-input]" class="form-control form-control-inline"
                               value="Assi Brasil">
                    </div>

                    <div class="mt-repeater-input">
                        <a href="javascript:;" data-repeater-delete=""
                           class="btn btn-danger mt-repeater-delete">
                            <i class="fa fa-close"></i> Delete</a>
                    </div>

                </div>

            </div>
            <a href="javascript:;" data-repeater-create class="btn btn-success mt-repeater-add">
                <i class="fa fa-plus"></i> Add</a>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $('.group-endereco').repeater({
            // (Required if there is a nested repeater)
            // Specify the configuration of the nested repeaters.
            // Nested configuration follows the same format as the base configuration,
            // supporting options "defaultValues", "show", "hide", etc.
            // Nested repeaters additionally require a "selector" field.
            repeaters: [{
                // (Required)
                // Specify the jQuery selector for this nested repeater
                selector: '.group-endereco'
            }],
            // (Optional)
            // "show" is called just after an item is added.  The item is hidden
            // at this point.  If a show callback is not given the item will
            // have $(this).show() called on it.
            show: function () {
                $(this).slideDown();
            },
            // (Optional)
            // "hide" is called when a user clicks on a data-repeater-delete
            // element.  The item is still visible.  "hide" is passed a function
            // as its first argument which will properly remove the item.
            // "hide" allows for a confirmation step, to send a delete request
            // to the server, etc.  If a hide callback is not given the item
            // will be deleted.
            hide: function (deleteElement) {
                if (confirm('Are you sure you want to delete this element?')) {
                    $(this).slideUp(deleteElement);
                }
            },
        });
        $('.group-telefone').repeater({
            // (Required if there is a nested repeater)
            // Specify the configuration of the nested repeaters.
            // Nested configuration follows the same format as the base configuration,
            // supporting options "defaultValues", "show", "hide", etc.
            // Nested repeaters additionally require a "selector" field.
            repeaters: [{
                // (Required)
                // Specify the jQuery selector for this nested repeater
                selector: '.group-telefone'
            }],
            // (Optional)
            // "show" is called just after an item is added.  The item is hidden
            // at this point.  If a show callback is not given the item will
            // have $(this).show() called on it.
            show: function () {
                $(this).slideDown();
            },
            // (Optional)
            // "hide" is called when a user clicks on a data-repeater-delete
            // element.  The item is still visible.  "hide" is passed a function
            // as its first argument which will properly remove the item.
            // "hide" allows for a confirmation step, to send a delete request
            // to the server, etc.  If a hide callback is not given the item
            // will be deleted.
            hide: function (deleteElement) {
                if (confirm('Are you sure you want to delete this element?')) {
                    $(this).slideUp(deleteElement);
                }
            },
        });
    });
</script>
