<h1>Cadastrar Veiculo</h1>
<div class="mt-element-step">
    <div class="row step-line">
        <div class="col-md-4 mt-step-col first active">
            <div class="mt-step-number bg-white">
                <i class="fa fa-car"></i>
            </div>
            <div class="mt-step-title uppercase font-grey-cascade">Veiculo</div>
            <div class="mt-step-content font-grey-cascade">Dados do veiculo</div>
        </div>
        <div class="col-md-4 mt-step-col active">
            <div class="mt-step-number bg-white">
                <i class="fa fa-user"></i>
            </div>
            <div class="mt-step-title uppercase font-grey-cascade">Cliente</div>
            <div class="mt-step-content font-grey-cascade">Dados do cliente</div>
        </div>
        <div class="col-md-4 mt-step-col last">
            <div class="mt-step-number bg-white">
                <i class="fa fa-rocket"></i>
            </div>
            <div class="mt-step-title uppercase font-grey-cascade">Fipe</div>
            <div class="mt-step-content font-grey-cascade">Selecione tabela Fipe</div>
        </div>
    </div>
</div>

<form class="mt-repeater form-horizontal" role="form">
    <div class="form-body">
        <h3 class="form-section">Proprietario</h3>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Nome:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> Bob </p>
                    </div>
                </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Cpf:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> Nilson </p>
                    </div>
                </div>
            </div>
            <!--/span-->
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Email:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> Bob </p>
                    </div>
                </div>
            </div>
        </div>
        <!--/row-->
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Sexo</label>
                    <div class="col-md-9">
                        <select class="form-control">
                            <option value="">Masculino</option>
                            <option value="">Female</option>
                        </select>
                        <span class="help-block"> Select your gender. </span>
                    </div>
                </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Nascimento:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> 20.01.1984 </p>
                    </div>
                </div>
            </div>

            <!--/span-->
        </div>
        <h3 class="form-section">Telefone</h3>
        <div class="row">
            <div class="col-md-9">
                <div class="form-group">
                    <label class="control-label col-md-3">Numero:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> (48) 84571624 </p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <a href="javascript:;" data-repeater-delete=""
                       class="btn btn-danger mt-repeater-delete">
                        <i class="fa fa-close"></i> Delete</a>
                </div>
            </div>
        </div>
        <!--/row-->
        <!--/row-->
        <h3 class="form-section">Endereço</h3>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Rua:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> #24 Sun Park Avenue, Rolton Str </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Cidade:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> New York </p>
                    </div>
                </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Estado:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> New York </p>
                    </div>
                </div>
            </div>
            <!--/span-->
        </div>
        <!--/row-->
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Cep:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> 457890 </p>
                    </div>
                </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">País:</label>
                    <div class="col-md-9">
                        <p class="form-control-static"> USA </p>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <div class="mt-repeater-input">
                        <a href="javascript:;" data-repeater-delete=""
                           class="btn btn-danger mt-repeater-delete">
                            <i class="fa fa-close"></i> Delete</a>
                    </div>
                </div>
            </div>
            <!--/span-->
        </div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <a href="javascript:;" data-repeater-create="" class="btn btn-success mt-repeater-add">
                            <i class="fa fa-plus"></i> Add</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6"></div>
        </div>
    </div>
</form>


<div class="portlet box red">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Repeating Forms
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
            <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title=""> </a>
            <a href="javascript:;" class="reload" data-original-title="" title=""> </a>
            <a href="javascript:;" class="remove" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <div class="form-body">
            <div class="form-group">
                <form action="#" class="mt-repeater form-horizontal">
                    <h3 class="mt-repeater-title">Human Resource Management</h3>
                    <div data-repeater-list="group-a">

                        <div data-repeater-item="" class="mt-repeater-item">
                            <!-- jQuery Repeater Container -->
                            <div class="mt-repeater-input">
                                <label class="control-label">Name</label>
                                <br>
                                <input type="text" name="group-a[0][text-input]" class="form-control"
                                       value="John Smith"></div>
                            <div class="mt-repeater-input">
                                <label class="control-label">Joined Date</label>
                                <br>
                                <input class="input-group form-control form-control-inline date date-picker" size="16"
                                       type="text" value="01/08/2016" name="group-a[0][date-input]"
                                       data-date-format="dd/mm/yyyy"></div>
                            <div class="mt-repeater-input mt-repeater-textarea">
                                <label class="control-label">Job Description</label>
                                <br>
                                <textarea name="group-a[0][textarea-input]" class="form-control" rows="3">This role is to follow up with all meetings and ensure that each operational process flow moves accordingly in a timely manner.</textarea>
                            </div>
                            <div class="mt-repeater-input mt-radio-inline">
                                <label class="control-label">Tier</label>
                                <br>
                                <label class="mt-radio">
                                    <input type="radio" name="group-a[0][optionsRadios]" id="optionsRadios25"
                                           value="junior"> Junior
                                    <span></span>
                                </label>
                                <label class="mt-radio">
                                    <input type="radio" name="group-a[0][optionsRadios]" id="optionsRadios26"
                                           value="senior"> Senior
                                    <span></span>
                                </label>
                            </div>
                            <div class="mt-repeater-input mt-checkbox-inline">
                                <label class="control-label">Language</label>
                                <br>
                                <label class="mt-checkbox">
                                    <input type="checkbox" id="inlineCheckbox21" value="option1"> English
                                    <span></span>
                                </label>
                                <label class="mt-checkbox">
                                    <input type="checkbox" id="inlineCheckbox22" value="option2"> French
                                    <span></span>
                                </label>
                            </div>
                            <div class="mt-repeater-input">
                                <label class="control-label">Department</label>
                                <br>
                                <select name="group-a[0][select-input]" class="form-control">
                                    <option value="A" selected="">Marketing</option>
                                    <option value="B">Creative</option>
                                    <option value="C">Development</option>
                                </select>
                            </div>
                            <div class="mt-repeater-input">
                                <a href="javascript:;" data-repeater-delete=""
                                   class="btn btn-danger mt-repeater-delete">
                                    <i class="fa fa-close"></i> Delete</a>
                            </div>
                        </div>
                        <div data-repeater-item="" class="mt-repeater-item">
                            <!-- jQuery Repeater Container -->
                            <div class="mt-repeater-input">
                                <label class="control-label">Name</label>
                                <br>
                                <input type="text" name="group-a[1][text-input]" class="form-control"
                                       value="John Smith"></div>
                            <div class="mt-repeater-input">
                                <label class="control-label">Joined Date</label>
                                <br>
                                <input class="input-group form-control form-control-inline date date-picker" size="16"
                                       type="text" value="01/08/2016" name="group-a[1][date-input]"
                                       data-date-format="dd/mm/yyyy"></div>
                            <div class="mt-repeater-input mt-repeater-textarea">
                                <label class="control-label">Job Description</label>
                                <br>
                                <textarea name="group-a[1][textarea-input]" class="form-control" rows="3">This role is to follow up with all meetings and ensure that each operational process flow moves accordingly in a timely manner.</textarea>
                            </div>
                            <div class="mt-repeater-input mt-radio-inline">
                                <label class="control-label">Tier</label>
                                <br>
                                <label class="mt-radio">
                                    <input type="radio" name="group-a[1][optionsRadios]" id="optionsRadios25"
                                           value="junior"> Junior
                                    <span></span>
                                </label>
                                <label class="mt-radio">
                                    <input type="radio" name="group-a[1][optionsRadios]" id="optionsRadios26"
                                           value="senior"> Senior
                                    <span></span>
                                </label>
                            </div>
                            <div class="mt-repeater-input mt-checkbox-inline">
                                <label class="control-label">Language</label>
                                <br>
                                <label class="mt-checkbox">
                                    <input type="checkbox" id="inlineCheckbox21" value="option1"> English
                                    <span></span>
                                </label>
                                <label class="mt-checkbox">
                                    <input type="checkbox" id="inlineCheckbox22" value="option2"> French
                                    <span></span>
                                </label>
                            </div>
                            <div class="mt-repeater-input">
                                <label class="control-label">Department</label>
                                <br>
                                <select name="group-a[1][select-input]" class="form-control">
                                    <option value="A" selected="">Marketing</option>
                                    <option value="B">Creative</option>
                                    <option value="C">Development</option>
                                </select>
                            </div>
                            <div class="mt-repeater-input">
                                <a href="javascript:;" data-repeater-delete=""
                                   class="btn btn-danger mt-repeater-delete">
                                    <i class="fa fa-close"></i> Delete</a>
                            </div>
                        </div>
                    </div>
                    <a href="javascript:;" data-repeater-create="" class="btn btn-success mt-repeater-add">
                        <i class="fa fa-plus"></i> Add</a>
                </form>
            </div>
        </div>
    </div>
</div>