<?php
use Avaliacao\Lib\Enum\RoutesEnum;

$this->headTitle("Veiculos");
?>
<!-- END THEME PANEL -->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="<?= $this->url('home'); ?>">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="<?= $this->url(RoutesEnum::VEICULO); ?>">Veiculos</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Detalhes</span>
        </li>
    </ul>
</div>


<!-- BEGIN PAGE TITLE-->
<h1 class="page-title"> Veiculos
    <small>listagem de veiculos</small>
    <a class="pull-right btn btn-circle btn-sm btn-default active"
       href="<?= $this->url(RoutesEnum::VEICULO); ?>">
        Voltar
    </a>
</h1>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Dados do veiculo</h3>
    </div>
    <div class="panel-body">
        <div class="row marketing">
            <?= $this->partial('veiculo/label', ['veiculo' => $veiculo]); ?>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Cliente</h3>
    </div>

    <div class="panel-body">
        <?php if (is_null($veiculo->getCliente())): ?>
            <p>Cliente não cadastrado</p>
            <a class="btn btn-sm btn-default active"
               href="<?= $this->url(RoutesEnum::VEICULO, ['action' => 'cliente','id'=>$veiculo->getId()]); ?>">
                Cadastrar
            </a>
        <?php else: ?>
            <div class="row marketing">
                <div class="col-lg-6">
                    <label>Nome</label> - <span><?php echo $veiculo->getCliente()->getNome() ?></span>
                </div>

                <?php if ($veiculo->getCliente()->getTipo() == 'Fisica'): ?>
                    <div class="col-lg-6">
                        <label>Cpf</label> - <span><?php echo $veiculo->getCliente()->getCpfCnpj(); ?></span>
                    </div>
                    <div class="col-lg-6">
                        <label>Sexo</label> - <span><?php echo $veiculo->getCliente()->getSexo(); ?></span>
                    </div>
                <?php else: ?>
                    <div class="col-lg-6">
                        <label>Cnpj</label> - <span><?php echo $veiculo->getCliente()->getCpfCnpj(); ?></span>
                    </div>
                <?php endif; ?>
                <div class="col-lg-6">
                    <label>Email</label> - <span><?php echo $veiculo->getCliente()->getEmail(); ?></span>
                </div>

                <div class="col-lg-6">
                    <label>Nascimento</label> - <span><?php echo $this->dateFormat(
                            $veiculo->getCliente()->getData(),
                            IntlDateFormatter::MEDIUM, // date
                            IntlDateFormatter::NONE, // time
                            "pt_BR"
                        ); ?></span>
                </div>
            </div>
            <div class="row marketing">
                <h4 style="margin-left: 10px;">Endereços</h4>
                <?php foreach ($veiculo->getCliente()->getEnderecos() as $key => $val): ?>
                    <div class="col-lg-12">
                        <address>
                            <i class="fa fa-home fa-lg"></i>
                            <?= $val->getLogradouro() ?>, <?= $val->getNumero() ?>,<?= $val->getComplemento() ?>
                            <?= $val->getBairro() ?> <?= $val->getCidade() ?>
                            , <?= $val->getUf() ?> <?= $val->getCep() ?>
                        </address>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="row marketing">

                <h4 style="margin-left: 10px;">Telefones</h4>
                <?php foreach ($veiculo->getCliente()->getTelefones() as $key => $val): ?>
                    <div class="col-lg-6">
                        <?php if ($val->isWhatsapp()): ?>
                            <i class="fa fa-mobile fa-lg"></i>
                        <?php else: ?>
                            <i style="color: green" class="fa fa-whatsapp"></i>
                        <?php endif; ?>
                        Telefone <?= $val->getTipo(); ?> - <?= $val->getNumero(); ?>
                    </div>
                <?php endforeach; ?>


            </div>
        <?php endif; ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-lg-10">
                <h3 class="panel-title">Avaliações</h3>
            </div>
            <div class="col-lg-2">
                <a class="pull-right btn btn-circle btn-sm btn-default active"
                   href="<?= $this->url(RoutesEnum::FIPE, ['action' => 'avaliar', 'id' => $veiculo->getId()]); ?>">
                    Avaliar
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">

        <?php if (!count($veiculo->getAvaliacoes()) > 0): ?>
            <p>Sem Avaliações</p>
        <?php else: ?>
            <table class="table table-striped table-bordered table-hover " width="100%" id="veiculosTable">
                <thead>
                <tr>
                    <th class="all">Avaliador</th>
                    <th class="none">Valor Avaliacao</th>
                    <th class="none">Cotação Fipe</th>
                    <th class="none">Pneu</th>
                    <th class="none">Quilometragem</th>
                    <th class="none">Obs</th>
                    <th class="none">Data Avaliação</th>
                    <th class="none">Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php
                /** @var $avaliacao \Avaliacao\Entity\AvaliacaoFipe */
                foreach ($veiculo->getAvaliacoes() as $avaliacao): ?>
                    <tr>
                        <td><?= $this->escapeHtml($avaliacao->getAvaliador()->getFullName()); ?></td>
                        <td><?= $this->currencyFormat($avaliacao->getValor(), 'BRL', true, 'pt_BR'); ?></td>
                        <td><?= $this->escapeHtml($avaliacao->getValorFipe()); ?></td>
                        <td><?= $this->escapeHtml($avaliacao->getPneu()); ?></td>
                        <td><?= $this->escapeHtml($avaliacao->getQuilometragem()); ?> KM</td>
                        <td><?= $this->escapeHtml($avaliacao->getObs()); ?></td>
                        <td><?php echo $this->dateFormat(
                                $avaliacao->getCreated(),
                                IntlDateFormatter::MEDIUM, // date
                                IntlDateFormatter::MEDIUM, // time
                                "pt_BR"
                            ); ?>
                        <td>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

        <?php endif; ?>
    </div>
</div>