<?php $this->headTitle("Veiculo"); ?>

<div class="row">
    <div class="thumbnail">
        <div class="caption">
            <h2><?= $this->escapeHtml($veiculo->getPlaca()); ?></h2>
            <hr/>
            <div class="form-group">
                <label class="col-sm-2 control-label">Placa</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $veiculo->getPlaca();?></p>
                </div>
            </div>
        </div>
    </div>
    <div class="well well-lg">
        <h4>Anotações</h4>
        <br/><br/><br/>
        <ul>
            <li><?= $this->escapeHtml('sdfsdfss') ?></li>
        </ul>
    </div>
</div>
