<?php
use Avaliacao\Lib\Enum\RoutesEnum;

$this->headTitle("Veiculos");
?>
<!-- END THEME PANEL -->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="<?= $this->url('home'); ?>">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="<?= $this->url(RoutesEnum::VEICULO); ?>">Veiculos</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Detalhes</span>
        </li>
    </ul>
</div>


<!-- BEGIN PAGE TITLE-->
<h1 class="page-title"> Veiculos
    <small>listagem de veiculos</small>
    <a class="pull-right btn btn-circle btn-sm btn-info active"
       href="<?= $this->url(RoutesEnum::VEICULO); ?>">
        Adicionar
    </a>
</h1>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Dados do veiculo</h3>
    </div>
    <div class="panel-body">
        <div class="row marketing">
            <?= $this->partial('veiculo/label', ['veiculo' => $veiculo]); ?>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Cliente</h3>
    </div>
    <div class="panel-body">
        <div class="row marketing">
            <div class="col-lg-6">
                <label>Nome</label> - <span><?php echo $veiculo->getCliente()->getNome(); ?></span>
            </div>

            <?php if ($veiculo->getCliente()->getTipo() == 'Fisica'): ?>
                <div class="col-lg-6">
                    <label>Cpf</label> - <span><?php echo $veiculo->getCliente()->getCpfCnpj(); ?></span>
                </div>
                <div class="col-lg-6">
                    <label>Sexo</label> - <span><?php echo $veiculo->getCliente()->getSexo(); ?></span>
                </div>
            <?php else: ?>
                <div class="col-lg-6">
                    <label>Cnpj</label> - <span><?php echo $veiculo->getCliente()->getCpfCnpj(); ?></span>
                </div>
            <?php endif; ?>
            <div class="col-lg-6">
                <label>Email</label> - <span><?php echo $veiculo->getCliente()->getEmail(); ?></span>
            </div>

            <div class="col-lg-6">
                <label>Nascimento</label> - <span><?php echo $this->dateFormat(
                        $veiculo->getCliente()->getData(),
                        IntlDateFormatter::MEDIUM, // date
                        IntlDateFormatter::NONE, // time
                        "pt_BR"
                    ); ?></span>
            </div>
            <h4 style="margin-left: 10px;">Endereços</h4>
            <?php foreach ($veiculo->getCliente()->getEnderecos() as $key => $val): ?>
                <div class="col-lg-12">
                    <address>
                        <i class="fa fa-home fa-lg"></i>
                        <?= $val->getLogradouro() ?>, <?= $val->getNumero() ?>,<?= $val->getComplemento() ?>
                        <?= $val->getBairro() ?> <?= $val->getCidade() ?>, <?= $val->getUf() ?> <?= $val->getCep() ?>
                    </address>
                </div>
            <?php endforeach; ?>

            <h4 style="margin-left: 10px;">Telefones</h4>
            <?php foreach ($veiculo->getCliente()->getTelefones() as $key => $val): ?>
                <div class="col-lg-6">
                    <?php if ($val->isWhatsapp()): ?>
                        <i class="fa fa-mobile fa-lg"></i>
                    <?php else: ?>
                        <i style="color: green" class="fa fa-whatsapp"></i>
                    <?php endif; ?>
                    Telefone <?= $val->getTipo(); ?> - <?= $val->getNumero(); ?>
                </div>
            <?php endforeach; ?>


        </div>
    </div>
</div>

