<h1>Avaliação Fipe</h1>
<?php

$tipo = $form->get('tipo');
$tipo->setAttribute('class', 'form-control')
    ->setLabel('Selecione o tipo')
    ->setLabelAttributes(['class' => 'control-label']);

$marca = $form->get('marca');
$marca->setAttribute('class', 'form-control')
    ->setLabel('Selecione a marca')
    ->setLabelAttributes(['class' => 'control-label']);

$modelo = $form->get('modelo');
$modelo->setAttribute('class', 'form-control')
    ->setLabel('Selecione o modelo')
    ->setLabelAttributes(['class' => 'control-label']);

$ano = $form->get('ano');
$ano->setAttribute('class', 'form-control')
    ->setLabel('Selecione o Ano')
    ->setLabelAttributes(['class' => 'control-label']);

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-success');

$form->setAttribute('action', $this->url(Avaliacao\Lib\Enum\RoutesEnum::FIPE, ['action' => 'avaliar','id' => $veiculo->getId()]));
$form->prepare();
?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Dados do veiculo</h3>
    </div>
    <div class="panel-body">
        <div class="row marketing">
            <?= $this->partial('veiculo/label', ['veiculo' => $veiculo]); ?>
        </div>
    </div>
</div>



<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Tabela Fipe</h3>
    </div>
    <div class="panel-body">
        <div class="portlet-body form">

            <?php echo $this->form()->openTag($form); ?>

            <?php $message = $this->formElementErrors($tipo, ['class' => 'help-block']); ?>

            <div class="form-group<?= $message ? " has-error" : "" ?>">
                <?= $this->formLabel($tipo); ?>
                <?= $this->formElement($tipo); ?>
                <?= $message ?>
            </div>

            <?php $message = $this->formElementErrors($marca, ['class' => 'help-block']); ?>

            <div class="form-group<?= $message ? " has-error" : "" ?>">
                <?= $this->formLabel($marca); ?>
                <?= $this->formElement($marca); ?>
                <?= $message ?>
            </div>

            <?php $message = $this->formElementErrors($modelo, ['class' => 'help-block']); ?>

            <div class="form-group<?= $message ? " has-error" : "" ?>">
                <?= $this->formLabel($modelo); ?>
                <?= $this->formElement($modelo); ?>
                <?= $message ?>
            </div>

            <?php $message = $this->formElementErrors($ano, ['class' => 'help-block']); ?>

            <div class="form-group<?= $message ? " has-error" : "" ?>">
                <?= $this->formLabel($ano); ?>
                <?= $this->formElement($ano); ?>
                <?= $message ?>
            </div>

            <div id='#fipe-div' style="display: none;" class="panel panel-default">
                <div class="panel-heading">
                    Dados Fipe
                </div>
                <div class="panel-body">
                    <div class="row marketing">
                        <div class="col-lg-6">
                            <label>Ano/Modelo</label> - <span id="campo_ano_modelo"></span>
                        </div>
                        <div class="col-lg-6">
                            <label>Codigo Fipe</label> - <span id="campo_codigo_fipe"></span>
                        </div>
                        <div class="col-lg-6">
                            <label>Combustivel</label> - <span id="campo_sigla_combustivel"></span> - <span id="campo_combustivel"></span>
                        </div>
                        <div class="col-lg-6">
                            <label>Marca</label> - <span id="campo_marca"></span>
                        </div>
                        <div class="col-lg-6">
                            <label>Mês Referência</label> - <span id="campo_mes_referencia"></span>
                        </div>
                        <div class="col-lg-6">
                            <label>Modelo</label> - <span id="campo_modelo"></span>
                        </div>
                        <div class="col-lg-6">
                            <label>Valor</label> - <span id="campo_valor"></span>
                        </div>
                    </div>
                </div>
            </div>

            <div id='#action-div' style="display: none;"  class="form-actions right">
                <?php
                    echo $this->formHidden($form->get('codigo'));
                    echo $this->formHidden($form->get('valor_fipe'));
                    echo $this->formSubmit($submit);
                ?>
            </div>

            <?php echo $this->form()->closeTag(); ?>

        </div>
    </div>
</div>


<script>

    $(function () {

        var tipo = $('#select-tipo');
        var marca = $('#select-marca');
        var modelo = $('#select-modelo');
        var ano = $('#select-ano');
        var codigo = $('#codigo-fipe');

        tipo.change(function () {

            if (tipo.val() != '') {
                $.ajax({
                    type: "POST",
                    url: "../get-marcas",
                    data: {tipo: tipo.val()},
                    success: function (result) {
                        marca.empty().append(function () {
                            var output = "<option>Selecione</option>";
                            $.each(result.marcas, function (key, value) {
                                output += "<option value='" + value.codigo + "' >" + value.nome + " </option>";
                            });
                            return output;
                        });
                        ano.empty();
                    }
                });

            }

        }).change();

        marca.change(function () {

            if (marca.val() != null) {
                $.ajax({
                    type: "POST",
                    url: "../get-modelos",
                    data: {tipo: tipo.val(),marca: marca.val()},
                    success: function (result) {

                        modelo.empty().append(function () {
                            var output = "<option>Selecione</option>";
                            $.each(result.modelos, function (key, value) {
                                output += "<option value='" + value.codigo + "' >" + value.nome + " </option>";
                            });
                            return output;
                        });
                        ano.empty();
                    }
                });

            }

        }).change();

        modelo.change(function () {

            if (marca.val() != null && modelo.val() != null) {
                $.ajax({
                    type: "POST",
                    url: "../get-anos",
                    data: {tipo: tipo.val(),marca: marca.val(), modelo: modelo.val()},
                    success: function (result) {
                        ano.empty().append(function () {
                            var output = "<option>Selecione</option>";
                            $.each(result.anos, function (key, value) {
                                output += "<option value='" + value.codigo + "' >" + value.nome + " </option>";
                            });
                            return output;
                        });
                    }
                });

            }

        }).change();


        ano.change(function () {

            if (marca.val() != null && modelo.val() != null && ano.val() != null) {
                $.ajax({
                    type: "POST",
                    url: "../get-veiculo",
                    data: {tipo: tipo.val(),marca: marca.val(), modelo: modelo.val(), ano: ano.val()},
                    success: function (result) {
                        document.getElementById('#fipe-div').style.display = 'block';
                        document.getElementById('#action-div').style.display = 'block';

                        $('#campo_ano_modelo').empty().append(function () {
                            return result.veiculo.AnoModelo
                        });
                        $('#campo_codigo_fipe').empty().append(function () {
                            return result.veiculo.CodigoFipe
                        });
                        $('#campo_combustivel').empty().append(function () {
                            return result.veiculo.Combustivel
                        });
                        $('#campo_marca').empty().append(function () {
                            return result.veiculo.Marca
                        });
                        $('#campo_mes_referencia').empty().append(function () {
                            return result.veiculo.MesReferencia
                        });
                        $('#campo_modelo').empty().append(function () {
                            return result.veiculo.Modelo
                        });
                        $('#campo_sigla_combustivel').empty().append(function () {
                            return result.veiculo.SiglaCombustivel
                        });
                        $('#campo_tipo_veiculo').empty().append(function () {
                            return result.veiculo.TipoVeiculo
                        });
                        $('#campo_valor').empty().append(function () {
                            return result.veiculo.Valor
                        });

                        $('#valor_fipe').val(result.veiculo.Valor);

                        codigo.val(result.veiculo.CodigoFipe);
                    }
                });
            }
        }).change();

    });
</script>