<h1>Avaliação Fipe</h1>
<?php

$form->setAttribute('action', $this->url(Avaliacao\Lib\Enum\RoutesEnum::FIPE, ['action' => 'observacao','id' => $id]));
$form->prepare();
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Dados do veiculo</h3>
    </div>
    <div class="panel-body">
        <div class="row marketing">
            <?= $this->partial('veiculo/label', ['veiculo' => $veiculo]); ?>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        Dados Fipe
    </div>
    <div class="panel-body">
        <div class="row marketing">
            <div class="col-lg-6">
                <label>Ano/Modelo</label> - <span><?php echo $fipe['AnoModelo']; ?></span>
            </div>
            <div class="col-lg-6">
                <label>Codigo Fipe</label> - <span><?php echo $fipe['CodigoFipe']; ?></span>
            </div>
            <div class="col-lg-6">
                <label>Combustivel</label> - <span><?php echo $fipe['SiglaCombustivel']; ?></span> - <?php echo $fipe['Combustivel']; ?></span>
            </div>
            <div class="col-lg-6">
                <label>Marca</label> - <?php echo $fipe['Marca']; ?></span>
            </div>
            <div class="col-lg-6">
                <label>Mês Referência</label> - <?php echo $fipe['MesReferencia']; ?></span>
            </div>
            <div class="col-lg-6">
                <label>Modelo</label> - <?php echo $fipe['Modelo']; ?></span>
            </div>
            <div class="col-lg-6">
                <label>Valor</label> - <?php echo $fipe['Valor']; ?></span>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Dados Extras</h3>
    </div>
    <div class="panel-body">
        <div class="portlet-body form">

            <?php echo $this->form()->openTag($form); ?>

            <?php $message = $this->formElementErrors($form->get('kilometragem'), ['class' => 'help-block']); ?>

            <div class="form-group<?= $message ? " has-error" : "" ?>">
                <?= $this->formLabel($form->get('kilometragem')); ?>
                <?= $this->formElement($form->get('kilometragem')); ?>
                <?= $message ?>
            </div>

            <?php $message = $this->formElementErrors($form->get('pneu'), ['class' => 'help-block']); ?>

            <div class="form-group<?= $message ? " has-error" : "" ?>">
                <?= $this->formLabel($form->get('pneu')); ?>
                <?= $this->formElement($form->get('pneu')); ?>
                <?= $message ?>
            </div>

            <?php $message = $this->formElementErrors($form->get('obs'), ['class' => 'help-block']); ?>

            <div class="form-group<?= $message ? " has-error" : "" ?>">
                <?= $this->formLabel($form->get('obs')); ?>
                <?= $this->formElement($form->get('obs')); ?>
                <?= $message ?>
            </div>

            <?php $message = $this->formElementErrors($form->get('valor'), ['class' => 'help-block']); ?>

            <div class="form-group<?= $message ? " has-error" : "" ?>">
                <?= $this->formLabel($form->get('valor')); ?>
                <?= $this->formElement($form->get('valor')); ?>
                <?= $message ?>
            </div>

            <div class="form-actions right">
                <?php
                echo $this->formHidden($form->get('id'));
                echo $this->formSubmit($form->get('submit'));
                ?>
            </div>

            <?php echo $this->form()->closeTag(); ?>

        </div>
    </div>
</div>
