<!--[if lt IE 9]>
<script src="<?= $this->basePath?>/assets/global/plugins/respond.min.js"></script>
<script src="<?= $this->basePath?>/assets/global/plugins/excanvas.min.js"></script>
<![endif]-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?= $this->basePath ?>/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="<?= $this->basePath ?>/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"
        type="text/javascript"></script>
<script src="<?= $this->basePath ?>/assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js"
        type="text/javascript"></script>
<script src="<?= $this->basePath ?>/js/jquery.maskMoney.min.js" type="text/javascript"></script>

<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="<?= $this->basePath ?>/assets/global/scripts/app.js" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN THEME LAYOUT SCRIPTS -->
<script src="<?= $this->basePath ?>/assets/layouts/layout/scripts/layout.min.js" type="text/javascript"></script>
<script src="<?= $this->basePath ?>/assets/layouts/layout/scripts/demo.min.js" type="text/javascript"></script>
<script src="<?= $this->basePath ?>/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>



<!-- END THEME LAYOUT SCRIPTS -->
<!-- END JAVASCRIPTS -->
<script>
    $(document).ready(function () {
        $('a[href="' + this.location.pathname + '"]').parent().addClass('active open').find('.arrow').addClass('open');
        $('a[href="' + this.location.pathname + '"]').parent().parent().parent().find('.arrow').addClass('open');
        $('a[href="' + this.location.pathname + '"]').parent().parent().parent().addClass('active open');
    });
</script>